"""initial tables

Revision ID: edb994c8263e
Revises: 
Create Date: 2026-06-07 17:45:02.160006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb994c8263e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('ad_script', sa.Text(), nullable=False),
    sa.Column('language', sa.Enum('hindi', 'nepali', 'english', name='languageenum'), nullable=True),
    sa.Column('monthly_fee_inr', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_sponsors_city'), 'ad_sponsors', ['city'], unique=False)
    op.create_index(op.f('ix_ad_sponsors_id'), 'ad_sponsors', ['id'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('category', sa.Enum('local', 'crime', 'accident', 'market_prices', 'real_estate', 'government', 'transport', 'weather', 'business', 'national', name='newscategory'), nullable=True),
    sa.Column('language', sa.Enum('hindi', 'nepali', 'english', name='languageenum'), nullable=True),
    sa.Column('importance_score', sa.Integer(), nullable=True),
    sa.Column('is_breaking', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('news_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_city'), 'news_items', ['city'], unique=False)
    op.create_index(op.f('ix_news_items_id'), 'news_items', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('language', sa.Enum('hindi', 'nepali', 'english', name='languageenum'), nullable=True),
    sa.Column('preferred_call_time', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'blocked', name='userstatusenum'), nullable=True),
    sa.Column('subscription_tier', sa.Enum('free', 'basic', 'premium', 'b2b', name='subscriptiontierenum'), nullable=True),
    sa.Column('calls_this_week', sa.Integer(), nullable=True),
    sa.Column('week_reset_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_call_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_city'), 'users', ['city'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('call_sid', sa.String(length=100), nullable=True),
    sa.Column('vapi_call_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'failed', 'missed', 'cancelled', name='callstatusenum'), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('news_items_delivered', sa.JSON(), nullable=True),
    sa.Column('script_used', sa.Text(), nullable=True),
    sa.Column('questions_asked', sa.JSON(), nullable=True),
    sa.Column('user_feedback', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('cost_inr', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_id'), 'call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_call_logs_scheduled_at'), 'call_logs', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_call_logs_status'), 'call_logs', ['status'], unique=False)
    op.create_index(op.f('ix_call_logs_user_id'), 'call_logs', ['user_id'], unique=False)
    op.create_table('reschedule_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_call_id', sa.Integer(), nullable=True),
    sa.Column('requested_time', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('raw_message', sa.String(length=500), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['original_call_id'], ['call_logs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reschedule_requests_id'), 'reschedule_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reschedule_requests_id'), table_name='reschedule_requests')
    op.drop_table('reschedule_requests')
    op.drop_index(op.f('ix_call_logs_user_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_status'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_scheduled_at'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_id'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_city'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_news_items_id'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_city'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_ad_sponsors_id'), table_name='ad_sponsors')
    op.drop_index(op.f('ix_ad_sponsors_city'), table_name='ad_sponsors')
    op.drop_table('ad_sponsors')
    # ### end Alembic commands ###
